name: Rotate Slideshow Image

on:
  schedule:
    - cron: "*/1 * * * *"  # 每分钟执行一次
  workflow_dispatch:       # 手动触发

permissions:
  contents: write

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rotate image
        run: |
          files=($(ls image/*))
          count=${#files[@]}
          idx=$((RANDOM % count))
          chosen=${files[$idx]}
          echo "Chosen file: $chosen"

          # 替换 README.md 中的占位符行
          sed -i "s|!\[Slideshow\](.*)|![Slideshow](${chosen}) <!--轮播占位符-->|" README.md

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Rotate slideshow image [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}


